[project]
name = "promptic-gradio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio~=5.3",
    "promptic~=2.1",
]

[tool.uv]
dev-dependencies = [
    "pyinstaller>=6.11.1",
    "pyloid>=0.17.4",
]
